
ccflags-y	+= -D__UD_STANDALONE__
obj-y		:= decode.o input.o itab.o kdbx_dis.o syn-att.o syn.o \
                   syn-intel.o udis86.o

clean:
	rm -f modules.order *.o .*.o.cmd modules.builtin built-in.mod.c 
